// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class ChiTietKiemKe
{
    public int MaCTKK { get; set; }

    public int? MaPhieuKK { get; set; }

    public int? MaVT { get; set; }

    public decimal SoLuongTheoSoSach { get; set; }

    public decimal SoLuongThucTe { get; set; }

    public decimal ChenhLech { get; set; }

    public string LyDo { get; set; }

    public virtual KiemKeKho MaPhieuKKNavigation { get; set; }

    public virtual VatTu MaVTNavigation { get; set; }
}