// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class ChiTietPhieuNhap
{
    public int MaCTPN { get; set; }

    public int? MaPhieuNhap { get; set; }

    public int? MaVT { get; set; }

    public decimal SoLuong { get; set; }

    public decimal DonGia { get; set; }

    public decimal ThanhTien { get; set; }

    public string GhiChu { get; set; }

    public virtual PhieuNhapKho MaPhieuNhapNavigation { get; set; }

    public virtual VatTu MaVTNavigation { get; set; }
}