// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class ChiTietDieuChuyen
{
    public int MaCTDC { get; set; }

    public int? MaDieuChuyen { get; set; }

    public int? MaVT { get; set; }

    public decimal SoLuong { get; set; }

    public string GhiChu { get; set; }

    public virtual DieuChuyenKho MaDieuChuyenNavigation { get; set; }

    public virtual VatTu MaVTNavigation { get; set; }
}