// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class ChiTietPhuTung
{
    public int MaChiTiet { get; set; }

    public int? MaPhieu { get; set; }

    public string TenPhuTung { get; set; }

    public int? SoLuong { get; set; }

    public string DonViTinh { get; set; }

    public string GhiChu { get; set; }

    public virtual PhieuBaoTri MaPhieuNavigation { get; set; }
}