// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class ChiTietPhieuXuat
{
    public int MaCTPX { get; set; }

    public int? MaPhieuXuat { get; set; }

    public int? MaVT { get; set; }

    public decimal SoLuong { get; set; }

    public decimal DonGiaXuat { get; set; }

    public decimal ThanhTien { get; set; }

    public string GhiChu { get; set; }

    public virtual PhieuXuatKho MaPhieuXuatNavigation { get; set; }

    public virtual VatTu MaVTNavigation { get; set; }
}