// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class DieuChuyenKho
{
    public int MaDieuChuyen { get; set; }

    public string SoPhieu { get; set; }

    public DateTime? NgayDieuChuyen { get; set; }

    public int? MaKhoXuat { get; set; }

    public int? MaKhoNhan { get; set; }

    public string LyDo { get; set; }

    public int? NguoiLapPhieu { get; set; }

    public int? NguoiNhanHang { get; set; }

    public string TrangThai { get; set; }

    public string GhiChu { get; set; }

    public virtual ICollection<ChiTietDieuChuyen> ChiTietDieuChuyens { get; set; } = new List<ChiTietDieuChuyen>();

    public virtual Kho MaKhoNhanNavigation { get; set; }

    public virtual Kho MaKhoXuatNavigation { get; set; }

    public virtual NhanVien NguoiLapPhieuNavigation { get; set; }

    public virtual NhanVien NguoiNhanHangNavigation { get; set; }
}