// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class HinhAnhBaoTri
{
    public int MaHinhAnh { get; set; }

    public int? MaPhieu { get; set; }

    public string DuongDanHinhAnh { get; set; }

    public string LoaiHinhAnh { get; set; }

    public string MoTa { get; set; }

    public DateTime? NgayTao { get; set; }

    public virtual PhieuBaoTri MaPhieuNavigation { get; set; }
}