// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class KeHoachBaoTri
{
    public int MaKeHoach { get; set; }

    public string TieuDe { get; set; }

    public int? MaThietBi { get; set; }

    public string LoaiBaoTri { get; set; }

    public int? ChuKyBaoTri { get; set; }

    public DateOnly? NgayBatDau { get; set; }

    public DateOnly? NgayKetThuc { get; set; }

    public string MoTa { get; set; }

    public string TrangThai { get; set; }

    public int? NguoiTao { get; set; }

    public DateTime? NgayTao { get; set; }

    public virtual ThietBi MaThietBiNavigation { get; set; }

    public virtual NguoiDung NguoiTaoNavigation { get; set; }

    public virtual ICollection<PhieuBaoTri> PhieuBaoTris { get; set; } = new List<PhieuBaoTri>();
}