// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class Kho
{
    public int MaKho { get; set; }

    public string TenKho { get; set; }

    public string DiaChi { get; set; }

    public int? NguoiQuanLy { get; set; }

    public string GhiChu { get; set; }

    public virtual ICollection<DieuChuyenKho> DieuChuyenKhoMaKhoNhanNavigations { get; set; } = new List<DieuChuyenKho>();

    public virtual ICollection<DieuChuyenKho> DieuChuyenKhoMaKhoXuatNavigations { get; set; } = new List<DieuChuyenKho>();

    public virtual ICollection<KiemKeKho> KiemKeKhos { get; set; } = new List<KiemKeKho>();

    public virtual NhanVien NguoiQuanLyNavigation { get; set; }

    public virtual ICollection<PhieuNhapKho> PhieuNhapKhos { get; set; } = new List<PhieuNhapKho>();

    public virtual ICollection<PhieuXuatKho> PhieuXuatKhos { get; set; } = new List<PhieuXuatKho>();

    public virtual ICollection<TonKho> TonKhos { get; set; } = new List<TonKho>();
}