// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class KiemKeKho
{
    public int MaPhieuKK { get; set; }

    public string SoPhieu { get; set; }

    public DateOnly NgayKiemKe { get; set; }

    public int? MaKho { get; set; }

    public int? NguoiKiemKe { get; set; }

    public string LyDo { get; set; }

    public string TrangThai { get; set; }

    public string GhiChu { get; set; }

    public virtual ICollection<ChiTietKiemKe> ChiTietKiemKes { get; set; } = new List<ChiTietKiemKe>();

    public virtual Kho MaKhoNavigation { get; set; }

    public virtual NhanVien NguoiKiemKeNavigation { get; set; }
}