// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class LichSuSuCo
{
    public int MaSuCo { get; set; }

    public int? MaThietBi { get; set; }

    public string TieuDe { get; set; }

    public string MoTa { get; set; }

    public string MucDo { get; set; }

    public DateTime? ThoiGianPhatHien { get; set; }

    public int? NguoiBaoCao { get; set; }

    public string TrangThai { get; set; }

    public string GiaiPhap { get; set; }

    public DateTime? NgayXuLy { get; set; }

    public virtual ThietBi MaThietBiNavigation { get; set; }

    public virtual NhanVien NguoiBaoCaoNavigation { get; set; }
}