// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class LoaiThietBi
{
    public int MaLoai { get; set; }

    public string TenLoai { get; set; }

    public string MoTa { get; set; }

    public string TieuChuanAnToan { get; set; }

    public virtual ICollection<ThietBi> ThietBis { get; set; } = new List<ThietBi>();
}