// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class LoaiVatTu
{
    public int MaLoaiVT { get; set; }

    public string TenLoaiVT { get; set; }

    public string MoTa { get; set; }

    public virtual ICollection<VatTu> VatTus { get; set; } = new List<VatTu>();
}