// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class NguoiDung
{
    public int MaND { get; set; }

    public int? MaNV { get; set; }

    public string TenDangNhap { get; set; }

    public string MatKhau { get; set; }

    public int? MaQuyen { get; set; }

    public bool? TrangThai { get; set; }

    public DateTime? NgayTao { get; set; }

    public string Email { get; set; }

    public string SoDienThoai { get; set; }

    public string PhongBan { get; set; }

    public string ChucVu { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? LastLogin { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual NhanVien MaNVNavigation { get; set; }

    public virtual PhanQuyen MaQuyenNavigation { get; set; }

    public virtual ICollection<NhanVien> NhanViens { get; set; } = new List<NhanVien>();

    public virtual ICollection<LichSuSuCo> LichSuSuCos { get; set; } = new List<LichSuSuCo>();

    public virtual ICollection<Kho> Khos { get; set; } = new List<Kho>();
}