// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class NhaCungCap
{
    public int MaNCC { get; set; }

    public string TenNCC { get; set; }

    public string DiaChi { get; set; }

    public string SoDienThoai { get; set; }

    public string Email { get; set; }

    public string NguoiLienHe { get; set; }

    public string GhiChu { get; set; }

    public virtual ICollection<PhieuNhapKho> PhieuNhapKhos { get; set; } = new List<PhieuNhapKho>();

    public virtual ICollection<VatTu> VatTus { get; set; } = new List<VatTu>();
}