// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class NhanVien
{
    public int MaNV { get; set; }

    public string HoTen { get; set; }

    public string Email { get; set; }

    public string SoDienThoai { get; set; }

    public string ChucVu { get; set; }

    public string PhongBan { get; set; }

    public DateTime? NgayTao { get; set; }

    public bool? TrangThai { get; set; }

    public int? UserID { get; set; }

    public virtual ICollection<DieuChuyenKho> DieuChuyenKhoNguoiLapPhieuNavigations { get; set; } = new List<DieuChuyenKho>();

    public virtual ICollection<DieuChuyenKho> DieuChuyenKhoNguoiNhanHangNavigations { get; set; } = new List<DieuChuyenKho>();

    public virtual ICollection<KeHoachBaoTri> KeHoachBaoTris { get; set; } = new List<KeHoachBaoTri>();

    public virtual ICollection<Kho> Khos { get; set; } = new List<Kho>();

    public virtual ICollection<KiemKeKho> KiemKeKhos { get; set; } = new List<KiemKeKho>();

    public virtual ICollection<LichSuSuCo> LichSuSuCos { get; set; } = new List<LichSuSuCo>();

    public virtual ICollection<NguoiDung> NguoiDungs { get; set; } = new List<NguoiDung>();

    public virtual ICollection<PhieuBaoTri> PhieuBaoTriNguoiXacNhanNavigations { get; set; } = new List<PhieuBaoTri>();

    public virtual ICollection<PhieuBaoTri> PhieuBaoTriNhanVienThucHienNavigations { get; set; } = new List<PhieuBaoTri>();

    public virtual ICollection<PhieuNhapKho> PhieuNhapKhos { get; set; } = new List<PhieuNhapKho>();

    public virtual ICollection<PhieuXuatKho> PhieuXuatKhos { get; set; } = new List<PhieuXuatKho>();

    public virtual NguoiDung User { get; set; }

    public virtual ICollection<VatTu> VatTus { get; set; } = new List<VatTu>();
}