// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class PhieuXuatKho
{
    public int MaPhieuXuat { get; set; }

    public string SoPhieu { get; set; }

    public DateTime? NgayXuat { get; set; }

    public int? MaKhoXuat { get; set; }

    public int? MaPhieuBaoTri { get; set; }

    public string LyDoXuat { get; set; }

    public string NguoiNhanHang { get; set; }

    public int? NguoiLapPhieu { get; set; }

    public string TrangThai { get; set; }

    public string GhiChu { get; set; }

    public virtual ICollection<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; } = new List<ChiTietPhieuXuat>();

    public virtual Kho MaKhoXuatNavigation { get; set; }

    public virtual PhieuBaoTri MaPhieuBaoTriNavigation { get; set; }

    public virtual NhanVien NguoiLapPhieuNavigation { get; set; }
}