// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class PhieuNhapKho
{
    public int MaPhieuNhap { get; set; }

    public string SoPhieu { get; set; }

    public DateTime? NgayNhap { get; set; }

    public int? MaKhoNhap { get; set; }

    public int? MaNCC { get; set; }

    public string NguoiGiaoHang { get; set; }

    public string SoHoaDon { get; set; }

    public DateOnly? NgayHoaDon { get; set; }

    public decimal? TongTien { get; set; }

    public string GhiChu { get; set; }

    public int? NguoiLapPhieu { get; set; }

    public string TrangThai { get; set; }

    public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; } = new List<ChiTietPhieuNhap>();

    public virtual Kho MaKhoNhapNavigation { get; set; }

    public virtual NhaCungCap MaNCCNavigation { get; set; }

    public virtual NhanVien NguoiLapPhieuNavigation { get; set; }
}