// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class PhieuBaoTri
{
    public int MaPhieu { get; set; }

    public int? MaKeHoach { get; set; }

    public int? MaThietBi { get; set; }

    public int? NhanVienThucHien { get; set; }

    public DateTime? ThoiGianBatDau { get; set; }

    public DateTime? ThoiGianKetThuc { get; set; }

    public string TinhTrangTruocBT { get; set; }

    public string TinhTrangSauBT { get; set; }

    public string KetQua { get; set; }

    public string GhiChu { get; set; }

    public int? NguoiXacNhan { get; set; }

    public DateTime? NgayXacNhan { get; set; }

    public string TrangThai { get; set; }

    public virtual ICollection<ChiTietPhuTung> ChiTietPhuTungs { get; set; } = new List<ChiTietPhuTung>();

    public virtual ICollection<HinhAnhBaoTri> HinhAnhBaoTris { get; set; } = new List<HinhAnhBaoTri>();

    public virtual KeHoachBaoTri MaKeHoachNavigation { get; set; }

    public virtual ThietBi MaThietBiNavigation { get; set; }

    public virtual NhanVien NguoiXacNhanNavigation { get; set; }

    public virtual NhanVien NhanVienThucHienNavigation { get; set; }

    public virtual ICollection<PhieuXuatKho> PhieuXuatKhos { get; set; } = new List<PhieuXuatKho>();
}