// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BilcoManagement.Models;

public partial class QuanLyChatLuongSanPhamContext : DbContext
{
    public QuanLyChatLuongSanPhamContext()
    {
    }

    public QuanLyChatLuongSanPhamContext(DbContextOptions<QuanLyChatLuongSanPhamContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ChiTietDieuChuyen> ChiTietDieuChuyens { get; set; }

    public virtual DbSet<ChiTietKiemKe> ChiTietKiemKes { get; set; }

    public virtual DbSet<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }

    public virtual DbSet<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; }

    public virtual DbSet<ChiTietPhuTung> ChiTietPhuTungs { get; set; }

    public virtual DbSet<DieuChuyenKho> DieuChuyenKhos { get; set; }

    public virtual DbSet<DonViTinh> DonViTinhs { get; set; }

    public virtual DbSet<HinhAnhBaoTri> HinhAnhBaoTris { get; set; }

    public virtual DbSet<KeHoachBaoTri> KeHoachBaoTris { get; set; }

    public virtual DbSet<Kho> Khos { get; set; }

    public virtual DbSet<KiemKeKho> KiemKeKhos { get; set; }

    public virtual DbSet<LichSuSuCo> LichSuSuCos { get; set; }

    public virtual DbSet<LoaiThietBi> LoaiThietBis { get; set; }

    public virtual DbSet<LoaiVatTu> LoaiVatTus { get; set; }

    public virtual DbSet<NguoiDung> NguoiDungs { get; set; }

    public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }

    public virtual DbSet<NhanVien> NhanViens { get; set; }

    public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }

    public virtual DbSet<PhieuBaoTri> PhieuBaoTris { get; set; }

    public virtual DbSet<PhieuNhapKho> PhieuNhapKhos { get; set; }

    public virtual DbSet<PhieuXuatKho> PhieuXuatKhos { get; set; }

    public virtual DbSet<ThietBi> ThietBis { get; set; }

    public virtual DbSet<TonKho> TonKhos { get; set; }

    public virtual DbSet<VatTu> VatTus { get; set; }



    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ChiTietDieuChuyen>(entity =>
        {
            entity.HasKey(e => e.MaCTDC).HasName("PK__ChiTietD__1E4E40F5A1140704");

            entity.ToTable("ChiTietDieuChuyen");

            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.SoLuong).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.MaDieuChuyenNavigation).WithMany(p => p.ChiTietDieuChuyens)
                .HasForeignKey(d => d.MaDieuChuyen)
                .HasConstraintName("FK__ChiTietDi__MaDie__114A936A");

            entity.HasOne(d => d.MaVTNavigation).WithMany(p => p.ChiTietDieuChuyens)
                .HasForeignKey(d => d.MaVT)
                .HasConstraintName("FK__ChiTietDie__MaVT__123EB7A3");
        });

        modelBuilder.Entity<ChiTietKiemKe>(entity =>
        {
            entity.HasKey(e => e.MaCTKK).HasName("PK__ChiTietK__1E4E09D676825D5C");

            entity.ToTable("ChiTietKiemKe");

            entity.Property(e => e.ChenhLech).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LyDo).HasMaxLength(500);
            entity.Property(e => e.SoLuongTheoSoSach).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SoLuongThucTe).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.MaPhieuKKNavigation).WithMany(p => p.ChiTietKiemKes)
                .HasForeignKey(d => d.MaPhieuKK)
                .HasConstraintName("FK__ChiTietKi__MaPhi__1AD3FDA4");

            entity.HasOne(d => d.MaVTNavigation).WithMany(p => p.ChiTietKiemKes)
                .HasForeignKey(d => d.MaVT)
                .HasConstraintName("FK__ChiTietKie__MaVT__1BC821DD");
        });

        modelBuilder.Entity<ChiTietPhieuNhap>(entity =>
        {
            entity.HasKey(e => e.MaCTPN).HasName("PK__ChiTietP__1E4E6075C7DF3DEE");

            entity.ToTable("ChiTietPhieuNhap");

            entity.Property(e => e.DonGia).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.SoLuong).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ThanhTien).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.MaPhieuNhapNavigation).WithMany(p => p.ChiTietPhieuNhaps)
                .HasForeignKey(d => d.MaPhieuNhap)
                .HasConstraintName("FK__ChiTietPh__MaPhi__797309D9");

            entity.HasOne(d => d.MaVTNavigation).WithMany(p => p.ChiTietPhieuNhaps)
                .HasForeignKey(d => d.MaVT)
                .HasConstraintName("FK__ChiTietPhi__MaVT__7A672E12");
        });

        modelBuilder.Entity<ChiTietPhieuXuat>(entity =>
        {
            entity.HasKey(e => e.MaCTPX).HasName("PK__ChiTietP__1E4E606F9E359980");

            entity.ToTable("ChiTietPhieuXuat");

            entity.Property(e => e.DonGiaXuat).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.SoLuong).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ThanhTien).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.MaPhieuXuatNavigation).WithMany(p => p.ChiTietPhieuXuats)
                .HasForeignKey(d => d.MaPhieuXuat)
                .HasConstraintName("FK__ChiTietPh__MaPhi__04E4BC85");

            entity.HasOne(d => d.MaVTNavigation).WithMany(p => p.ChiTietPhieuXuats)
                .HasForeignKey(d => d.MaVT)
                .HasConstraintName("FK__ChiTietPhi__MaVT__05D8E0BE");
        });

        modelBuilder.Entity<ChiTietPhuTung>(entity =>
        {
            entity.HasKey(e => e.MaChiTiet).HasName("PK__ChiTietP__CDF0A114EFF388F8");

            entity.ToTable("ChiTietPhuTung");

            entity.Property(e => e.DonViTinh).HasMaxLength(20);
            entity.Property(e => e.GhiChu).HasMaxLength(200);
            entity.Property(e => e.SoLuong).HasDefaultValue(1);
            entity.Property(e => e.TenPhuTung)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.MaPhieuNavigation).WithMany(p => p.ChiTietPhuTungs)
                .HasForeignKey(d => d.MaPhieu)
                .HasConstraintName("FK__ChiTietPh__MaPhi__236943A5");
        });

        modelBuilder.Entity<DieuChuyenKho>(entity =>
        {
            entity.HasKey(e => e.MaDieuChuyen).HasName("PK__DieuChuy__750B0A6D91FDC6DB");

            entity.ToTable("DieuChuyenKho");

            entity.HasIndex(e => e.SoPhieu, "UQ__DieuChuy__960AAEE37F664455").IsUnique();

            entity.Property(e => e.GhiChu).HasMaxLength(500);
            entity.Property(e => e.LyDo).HasMaxLength(500);
            entity.Property(e => e.NgayDieuChuyen)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SoPhieu)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TrangThai)
                .HasMaxLength(50)
                .HasDefaultValue("Đã hoàn thành");

            entity.HasOne(d => d.MaKhoNhanNavigation).WithMany(p => p.DieuChuyenKhoMaKhoNhanNavigations)
                .HasForeignKey(d => d.MaKhoNhan)
                .HasConstraintName("FK__DieuChuye__MaKho__0B91BA14");

            entity.HasOne(d => d.MaKhoXuatNavigation).WithMany(p => p.DieuChuyenKhoMaKhoXuatNavigations)
                .HasForeignKey(d => d.MaKhoXuat)
                .HasConstraintName("FK__DieuChuye__MaKho__0A9D95DB");

            entity.HasOne(d => d.NguoiLapPhieuNavigation).WithMany(p => p.DieuChuyenKhoNguoiLapPhieuNavigations)
                .HasForeignKey(d => d.NguoiLapPhieu)
                .HasConstraintName("FK__DieuChuye__Nguoi__0C85DE4D");

            entity.HasOne(d => d.NguoiNhanHangNavigation).WithMany(p => p.DieuChuyenKhoNguoiNhanHangNavigations)
                .HasForeignKey(d => d.NguoiNhanHang)
                .HasConstraintName("FK__DieuChuye__Nguoi__0D7A0286");
        });

        modelBuilder.Entity<DonViTinh>(entity =>
        {
            entity.HasKey(e => e.MaDVT).HasName("PK__DonViTin__3D895AFE9C8B0713");

            entity.ToTable("DonViTinh");

            entity.Property(e => e.MoTa).HasMaxLength(200);
            entity.Property(e => e.TenDVT)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<HinhAnhBaoTri>(entity =>
        {
            entity.HasKey(e => e.MaHinhAnh).HasName("PK__HinhAnhB__A9C37A9B01F565F9");

            entity.ToTable("HinhAnhBaoTri");

            entity.Property(e => e.DuongDanHinhAnh)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.LoaiHinhAnh).HasMaxLength(50);
            entity.Property(e => e.MoTa).HasMaxLength(200);
            entity.Property(e => e.NgayTao)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.MaPhieuNavigation).WithMany(p => p.HinhAnhBaoTris)
                .HasForeignKey(d => d.MaPhieu)
                .HasConstraintName("FK__HinhAnhBa__MaPhi__2739D489");
        });

        modelBuilder.Entity<KeHoachBaoTri>(entity =>
        {
            entity.HasKey(e => e.MaKeHoach).HasName("PK__KeHoachB__88C5741FED66D971");

            entity.ToTable("KeHoachBaoTri");

            entity.Property(e => e.LoaiBaoTri)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.MoTa).HasMaxLength(500);
            entity.Property(e => e.NgayTao)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TieuDe)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.TrangThai)
                .HasMaxLength(50)
                .HasDefaultValue("Chưa thực hiện");

            entity.HasOne(d => d.MaThietBiNavigation).WithMany(p => p.KeHoachBaoTris)
                .HasForeignKey(d => d.MaThietBi)
                .HasConstraintName("FK__KeHoachBa__MaThi__4316F928");

            entity.HasOne(d => d.NguoiTaoNavigation).WithMany(p => p.KeHoachBaoTris)
                .HasForeignKey(d => d.NguoiTao)
                .HasConstraintName("FK__KeHoachBa__Nguoi__NguoiDung");
        });

        modelBuilder.Entity<Kho>(entity =>
        {
            entity.HasKey(e => e.MaKho).HasName("PK__Kho__3BDA9350F8F4FAC4");

            entity.ToTable("Kho");

            entity.Property(e => e.DiaChi).HasMaxLength(500);
            entity.Property(e => e.GhiChu).HasMaxLength(500);
            entity.Property(e => e.TenKho)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.NguoiQuanLyNavigation).WithMany(p => p.Khos)
                .HasForeignKey(d => d.NguoiQuanLyID)
                .HasConstraintName("FK__Kho__NguoiQuanLyID");
        });

        modelBuilder.Entity<KiemKeKho>(entity =>
        {
            entity.HasKey(e => e.MaPhieuKK).HasName("PK__KiemKeKh__880EE8E856CE8FF5");

            entity.ToTable("KiemKeKho");

            entity.HasIndex(e => e.SoPhieu, "UQ__KiemKeKh__960AAEE3724913EE").IsUnique();

            entity.Property(e => e.GhiChu).HasMaxLength(500);
            entity.Property(e => e.LyDo).HasMaxLength(500);
            entity.Property(e => e.SoPhieu)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TrangThai)
                .HasMaxLength(50)
                .HasDefaultValue("Đang kiểm kê");

            entity.HasOne(d => d.MaKhoNavigation).WithMany(p => p.KiemKeKhos)
                .HasForeignKey(d => d.MaKho)
                .HasConstraintName("FK__KiemKeKho__MaKho__160F4887");

            entity.HasOne(d => d.NguoiKiemKeNavigation).WithMany(p => p.KiemKeKhos)
                .HasForeignKey(d => d.NguoiKiemKe)
                .HasConstraintName("FK__KiemKeKho__Nguoi__17036CC0");
        });

        modelBuilder.Entity<LichSuSuCo>(entity =>
        {
            entity.HasKey(e => e.MaSuCo).HasName("PK__LichSuSu__A69DF79FCA6E092E");

            entity.ToTable("LichSuSuCo");

            entity.Property(e => e.GiaiPhap).HasMaxLength(1000);
            entity.Property(e => e.MoTa).HasMaxLength(1000);
            entity.Property(e => e.MucDo).HasMaxLength(50);
            entity.Property(e => e.NgayXuLy).HasColumnType("datetime");
            entity.Property(e => e.ThoiGianPhatHien).HasColumnType("datetime");
            entity.Property(e => e.TieuDe)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.TrangThai)
                .HasMaxLength(50)
                .HasDefaultValue("Chưa xử lý");

            entity.HasOne(d => d.MaThietBiNavigation).WithMany(p => p.LichSuSuCos)
                .HasForeignKey(d => d.MaThietBi)
                .HasConstraintName("FK__LichSuSuC__MaThi__1EA48E88");

            entity.HasOne(d => d.NguoiDung).WithMany(p => p.LichSuSuCos)
                .HasForeignKey(d => d.NguoiDungID)
                .HasConstraintName("FK__LichSuSuC__NguoiDungID");
        });

        modelBuilder.Entity<LoaiThietBi>(entity =>
        {
            entity.HasKey(e => e.MaLoai).HasName("PK__LoaiThie__730A5759B88BB5B9");

            entity.ToTable("LoaiThietBi");

            entity.Property(e => e.MoTa).HasMaxLength(500);
            entity.Property(e => e.TenLoai)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TieuChuanAnToan).HasMaxLength(200);
        });

        modelBuilder.Entity<LoaiVatTu>(entity =>
        {
            entity.HasKey(e => e.MaLoaiVT).HasName("PK__LoaiVatT__1224E204BED8466A");

            entity.ToTable("LoaiVatTu");

            entity.Property(e => e.MoTa).HasMaxLength(500);
            entity.Property(e => e.TenLoaiVT)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<NguoiDung>(entity =>
        {
            entity.HasKey(e => e.MaND).HasName("PK__NguoiDun__2725D724AAEA6ADE");

            entity.ToTable("NguoiDung");

            entity.HasIndex(e => e.TenDangNhap, "UQ__NguoiDun__55F68FC076A218F8").IsUnique();

            entity.Property(e => e.ChucVu).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LastLogin).HasColumnType("datetime");
            entity.Property(e => e.MatKhau)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.NgayTao)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PhongBan).HasMaxLength(100);
            entity.Property(e => e.SoDienThoai)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TenDangNhap)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TrangThai).HasDefaultValue(true);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.MaNVNavigation).WithMany(p => p.NguoiDungs)
                .HasForeignKey(d => d.MaNV)
                .HasConstraintName("FK__NguoiDung__MaNV__6B24EA82");

            entity.HasOne(d => d.MaQuyenNavigation).WithMany(p => p.NguoiDungs)
                .HasForeignKey(d => d.MaQuyen)
                .HasConstraintName("FK__NguoiDung__MaQuy__6C190EBB");
        });

        modelBuilder.Entity<NhaCungCap>(entity =>
        {
            entity.HasKey(e => e.MaNCC).HasName("PK__NhaCungC__3A185DEBE6AFAA11");

            entity.ToTable("NhaCungCap");

            entity.Property(e => e.DiaChi).HasMaxLength(500);
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.GhiChu).HasMaxLength(500);
            entity.Property(e => e.NguoiLienHe).HasMaxLength(100);
            entity.Property(e => e.SoDienThoai)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TenNCC)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<NhanVien>(entity =>
        {
            entity.HasKey(e => e.MaNV).HasName("PK__NhanVien__2725D70AA3601EA0");

            entity.ToTable("NhanVien");

            entity.HasIndex(e => e.Email, "UQ__NhanVien__A9D105344A132BAD").IsUnique();

            entity.Property(e => e.ChucVu).HasMaxLength(50);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.HoTen)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.NgayTao)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PhongBan).HasMaxLength(50);
            entity.Property(e => e.SoDienThoai)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.TrangThai).HasDefaultValue(true);

            entity.HasOne(d => d.User).WithMany(p => p.NhanViens)
                .HasForeignKey(d => d.UserID)
                .HasConstraintName("FK_NhanVien_NguoiDung");
        });

        modelBuilder.Entity<PhanQuyen>(entity =>
        {
            entity.HasKey(e => e.MaQuyen).HasName("PK__PhanQuye__1D4B7ED443CB0F65");

            entity.ToTable("PhanQuyen");

            entity.Property(e => e.MoTa).HasMaxLength(200);
            entity.Property(e => e.TenQuyen)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<PhieuBaoTri>(entity =>
        {
            entity.HasKey(e => e.MaPhieu).HasName("PK__PhieuBao__2660BFE02A7774C5");

            entity.ToTable("PhieuBaoTri");

            entity.Property(e => e.GhiChu).HasMaxLength(1000);
            entity.Property(e => e.KetQua).HasMaxLength(50);
            entity.Property(e => e.NgayDuyet).HasColumnType("datetime");
            entity.Property(e => e.ThoiGianBatDau).HasColumnType("datetime");
            entity.Property(e => e.ThoiGianKetThuc).HasColumnType("datetime");
            entity.Property(e => e.TinhTrangSauBT).HasMaxLength(200);
            entity.Property(e => e.TinhTrangTruocBT).HasMaxLength(200);
            entity.Property(e => e.TrangThai)
                .HasMaxLength(50)
                .HasDefaultValue("Chờ xác nhận");

            entity.HasOne(d => d.MaKeHoachNavigation).WithMany(p => p.PhieuBaoTris)
                .HasForeignKey(d => d.MaKeHoach)
                .HasConstraintName("FK__PhieuBaoT__MaKeH__48CFD27E");

            entity.HasOne(d => d.MaThietBiNavigation).WithMany(p => p.PhieuBaoTris)
                .HasForeignKey(d => d.MaThietBi)
                .HasConstraintName("FK__PhieuBaoT__MaThi__49C3F6B7");

            entity.HasOne(d => d.NguoiTaoNavigation).WithMany(p => p.PhieuBaoTriNguoiTaoNavigations)
                .HasForeignKey(d => d.NguoiTao)
                .HasConstraintName("FK__PhieuBaoT__NguoiT__4BAC3F29");

            entity.HasOne(d => d.NguoiDuyetNavigation).WithMany(p => p.PhieuBaoTriNguoiDuyetNavigations)
                .HasForeignKey(d => d.NguoiDuyet)
                .HasConstraintName("FK__PhieuBaoT__NguoiD__4AB81AF0");
        });

        modelBuilder.Entity<PhieuNhapKho>(entity =>
        {
            entity.HasKey(e => e.MaPhieuNhap).HasName("PK__PhieuNha__2660BFE02A7774C5");

            entity.ToTable("PhieuNhapKho");

            entity.HasIndex(e => e.SoPhieu, "UQ__PhieuNha__960AAEE3AF547A17").IsUnique();

            entity.Property(e => e.GhiChu).HasMaxLength(500);
            entity.Property(e => e.NgayNhap)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NguoiGiaoHang).HasMaxLength(100);
            entity.Property(e => e.SoHoaDon)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SoPhieu)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TongTien)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TrangThai)
                .HasMaxLength(50)
                .HasDefaultValue("Đã hoàn thành");

            entity.HasOne(d => d.MaKhoNhapNavigation).WithMany(p => p.PhieuNhapKhos)
                .HasForeignKey(d => d.MaKhoNhap)
                .HasConstraintName("FK__PhieuNhap__MaKho__72C60C4A");

            entity.HasOne(d => d.MaNCCNavigation).WithMany(p => p.PhieuNhapKhos)
                .HasForeignKey(d => d.MaNCC)
                .HasConstraintName("FK__PhieuNhap__MaNCC__73BA3083");

            entity.HasOne(d => d.NguoiLapPhieuNavigation).WithMany(p => p.PhieuNhapKhos)
                .HasForeignKey(d => d.NguoiLapPhieu)
                .HasConstraintName("FK__PhieuNhap__Nguoi__75A278F5");
        });

        modelBuilder.Entity<PhieuXuatKho>(entity =>
        {
            entity.HasKey(e => e.MaPhieuXuat).HasName("PK__PhieuXua__26C4B5A2FE7B5A65");

            entity.ToTable("PhieuXuatKho");

            entity.HasIndex(e => e.SoPhieu, "UQ__PhieuXua__960AAEE32DB10CF7").IsUnique();

            entity.Property(e => e.GhiChu).HasMaxLength(500);
            entity.Property(e => e.LyDoXuat).HasMaxLength(500);
            entity.Property(e => e.NgayXuat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NguoiNhanHang).HasMaxLength(100);
            entity.Property(e => e.SoPhieu)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TrangThai)
                .HasMaxLength(50)
                .HasDefaultValue("Đã hoàn thành");

            entity.HasOne(d => d.MaKhoXuatNavigation).WithMany(p => p.PhieuXuatKhos)
                .HasForeignKey(d => d.MaKhoXuat)
                .HasConstraintName("FK__PhieuXuat__MaKho__7F2BE32F");

            entity.HasOne(d => d.MaPhieuBaoTriNavigation).WithMany(p => p.PhieuXuatKhos)
                .HasForeignKey(d => d.MaPhieuBaoTri)
                .HasConstraintName("FK__PhieuXuat__MaPhi__00200768");

            entity.HasOne(d => d.NguoiLapPhieuNavigation).WithMany(p => p.PhieuXuatKhos)
                .HasForeignKey(d => d.NguoiLapPhieu)
                .HasConstraintName("FK__PhieuXuat__Nguoi__01142BA1");
        });

        modelBuilder.Entity<ThietBi>(entity =>
        {
            entity.HasKey(e => e.MaThietBi).HasName("PK__ThietBi__8AEC71F793B7F867");

            entity.ToTable("ThietBi");

            entity.HasIndex(e => e.MaSo, "UQ__ThietBi__2725087C40D5B15D").IsUnique();

            entity.Property(e => e.GhiChu).HasMaxLength(500);
            entity.Property(e => e.HinhAnh)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.MaSo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TenThietBi)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.TinhTrang)
                .HasMaxLength(50)
                .HasDefaultValue("Đang hoạt động");
            entity.Property(e => e.ViTriLapDat).HasMaxLength(200);

            entity.HasOne(d => d.MaLoaiNavigation).WithMany(p => p.ThietBis)
                .HasForeignKey(d => d.MaLoai)
                .HasConstraintName("FK__ThietBi__MaLoai__3F466844");
        });

        modelBuilder.Entity<TonKho>(entity =>
        {
            entity.HasKey(e => e.MaTonKho).HasName("PK__TonKho__2D970FAAD1B1B4E2");

            entity.ToTable("TonKho");

            entity.HasIndex(e => new { e.MaKho, e.MaVT }, "UQ__TonKho__C9A8C252169D38F0").IsUnique();

            entity.Property(e => e.NgayCapNhat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SoLuongKhaDung)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SoLuongToiThieu)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SoLuongTon)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ViTriLuuTru).HasMaxLength(100);

            entity.HasOne(d => d.MaKhoNavigation).WithMany(p => p.TonKhos)
                .HasForeignKey(d => d.MaKho)
                .HasConstraintName("FK__TonKho__MaKho__60A75C0F");

            entity.HasOne(d => d.MaVTNavigation).WithMany(p => p.TonKhos)
                .HasForeignKey(d => d.MaVT)
                .HasConstraintName("FK__TonKho__MaVT__619B8048");
        });

        modelBuilder.Entity<VatTu>(entity =>
        {
            entity.HasKey(e => e.MaVT).HasName("PK__VatTu__2725103E8899EE53");

            entity.ToTable("VatTu");

            entity.HasIndex(e => e.MaVach, "UQ__VatTu__8BBF4A1C9A1AEDA5").IsUnique();

            entity.Property(e => e.GhiChu).HasMaxLength(500);
            entity.Property(e => e.HinhAnh)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.MaVach)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NgayTao)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TenVT)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.MaDVTNavigation).WithMany(p => p.VatTus)
                .HasForeignKey(d => d.MaDVT)
                .HasConstraintName("FK__VatTu__MaDVT__571DF1D5");

            entity.HasOne(d => d.MaLoaiVTNavigation).WithMany(p => p.VatTus)
                .HasForeignKey(d => d.MaLoaiVT)
                .HasConstraintName("FK__VatTu__MaLoaiVT__5629CD9C");

            entity.HasOne(d => d.MaNCCNavigation).WithMany(p => p.VatTus)
                .HasForeignKey(d => d.MaNCC)
                .HasConstraintName("FK__VatTu__MaNCC__5812160E");

            entity.HasOne(d => d.NguoiTaoNavigation).WithMany(p => p.VatTus)
                .HasForeignKey(d => d.NguoiTao)
                .HasConstraintName("FK__VatTu__NguoiTao");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}