// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class ThietBi
{
    public int MaThietBi { get; set; }

    public string TenThietBi { get; set; }

    public int? MaLoai { get; set; }

    public string MaSo { get; set; }

    public string ViTriLapDat { get; set; }

    public DateOnly? NgayLapDat { get; set; }

    public DateOnly? NgayHetHanBaoHanh { get; set; }

    public string TinhTrang { get; set; }

    public string GhiChu { get; set; }

    public string HinhAnh { get; set; }

    public virtual ICollection<KeHoachBaoTri> KeHoachBaoTris { get; set; } = new List<KeHoachBaoTri>();

    public virtual ICollection<LichSuSuCo> LichSuSuCos { get; set; } = new List<LichSuSuCo>();

    public virtual LoaiThietBi MaLoaiNavigation { get; set; }

    public virtual ICollection<PhieuBaoTri> PhieuBaoTris { get; set; } = new List<PhieuBaoTri>();
}