// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class TonKho
{
    public int MaTonKho { get; set; }

    public int? MaKho { get; set; }

    public int? MaVT { get; set; }

    public decimal? SoLuongTon { get; set; }

    public decimal? SoLuongKhaDung { get; set; }

    public decimal? SoLuongToiThieu { get; set; }

    public string ViTriLuuTru { get; set; }

    public DateTime? NgayCapNhat { get; set; }

    public virtual Kho MaKhoNavigation { get; set; }

    public virtual VatTu MaVTNavigation { get; set; }
}