// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BilcoManagement.Models;

public partial class VatTu
{
    public int MaVT { get; set; }

    public int? MaLoaiVT { get; set; }

    public int? MaDVT { get; set; }

    public string TenVT { get; set; }

    public string MaVach { get; set; }

    public int? MaNCC { get; set; }

    public int? ThoiGianBaoHanh { get; set; }

    public string GhiChu { get; set; }

    public string HinhAnh { get; set; }

    public DateTime? NgayTao { get; set; }

    public int? NguoiTao { get; set; }

    public virtual ICollection<ChiTietDieuChuyen> ChiTietDieuChuyens { get; set; } = new List<ChiTietDieuChuyen>();

    public virtual ICollection<ChiTietKiemKe> ChiTietKiemKes { get; set; } = new List<ChiTietKiemKe>();

    public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; } = new List<ChiTietPhieuNhap>();

    public virtual ICollection<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; } = new List<ChiTietPhieuXuat>();

    public virtual DonViTinh MaDVTNavigation { get; set; }

    public virtual LoaiVatTu MaLoaiVTNavigation { get; set; }

    public virtual NhaCungCap MaNCCNavigation { get; set; }

    public virtual NhanVien NguoiTaoNavigation { get; set; }

    public virtual ICollection<TonKho> TonKhos { get; set; } = new List<TonKho>();
}