// <auto-generated />
using System;
using BilcoManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BilcoManagement.Migrations
{
    [DbContext(typeof(QuanLyChatLuongSanPhamContext))]
    partial class QuanLyChatLuongSanPhamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BilcoManagement.Models.ChiTietDieuChuyen", b =>
                {
                    b.Property<int>("MaCTDC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTDC"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaDieuChuyen")
                        .HasColumnType("int");

                    b.Property<int?>("MaVT")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaCTDC")
                        .HasName("PK__ChiTietD__1E4E40F5A1140704");

                    b.HasIndex("MaDieuChuyen");

                    b.HasIndex("MaVT");

                    b.ToTable("ChiTietDieuChuyen", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.ChiTietKiemKe", b =>
                {
                    b.Property<int>("MaCTKK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTKK"));

                    b.Property<decimal>("ChenhLech")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaPhieuKK")
                        .HasColumnType("int");

                    b.Property<int?>("MaVT")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuongTheoSoSach")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SoLuongThucTe")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaCTKK")
                        .HasName("PK__ChiTietK__1E4E09D676825D5C");

                    b.HasIndex("MaPhieuKK");

                    b.HasIndex("MaVT");

                    b.ToTable("ChiTietKiemKe", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaCTPN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTPN"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int?>("MaVT")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaCTPN")
                        .HasName("PK__ChiTietP__1E4E6075C7DF3DEE");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaVT");

                    b.ToTable("ChiTietPhieuNhap", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("MaCTPX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTPX"));

                    b.Property<decimal>("DonGiaXuat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaPhieuXuat")
                        .HasColumnType("int");

                    b.Property<int?>("MaVT")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaCTPX")
                        .HasName("PK__ChiTietP__1E4E606F9E359980");

                    b.HasIndex("MaPhieuXuat");

                    b.HasIndex("MaVT");

                    b.ToTable("ChiTietPhieuXuat", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.ChiTietPhuTung", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TenPhuTung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaChiTiet")
                        .HasName("PK__ChiTietP__CDF0A114EFF388F8");

                    b.HasIndex("MaPhieu");

                    b.ToTable("ChiTietPhuTung", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.DieuChuyenKho", b =>
                {
                    b.Property<int>("MaDieuChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDieuChuyen"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaKhoNhan")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhoXuat")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDieuChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("NguoiLapPhieu")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiNhanHang")
                        .HasColumnType("int");

                    b.Property<string>("SoPhieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đã hoàn thành");

                    b.HasKey("MaDieuChuyen")
                        .HasName("PK__DieuChuy__750B0A6D91FDC6DB");

                    b.HasIndex("MaKhoNhan");

                    b.HasIndex("MaKhoXuat");

                    b.HasIndex("NguoiLapPhieu");

                    b.HasIndex("NguoiNhanHang");

                    b.HasIndex(new[] { "SoPhieu" }, "UQ__DieuChuy__960AAEE37F664455")
                        .IsUnique();

                    b.ToTable("DieuChuyenKho", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.DonViTinh", b =>
                {
                    b.Property<int>("MaDVT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDVT"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenDVT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDVT")
                        .HasName("PK__DonViTin__3D895AFE9C8B0713");

                    b.ToTable("DonViTinh", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.HinhAnhBaoTri", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<string>("DuongDanHinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoaiHinhAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaHinhAnh")
                        .HasName("PK__HinhAnhB__A9C37A9B01F565F9");

                    b.HasIndex("MaPhieu");

                    b.ToTable("HinhAnhBaoTri", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.KeHoachBaoTri", b =>
                {
                    b.Property<int>("MaKeHoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKeHoach"));

                    b.Property<int?>("ChuKyBaoTri")
                        .HasColumnType("int");

                    b.Property<string>("LoaiBaoTri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa thực hiện");

                    b.HasKey("MaKeHoach")
                        .HasName("PK__KeHoachB__88C5741FED66D971");

                    b.HasIndex("MaThietBi");

                    b.HasIndex("NguoiTao");

                    b.ToTable("KeHoachBaoTri", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.Kho", b =>
                {
                    b.Property<int>("MaKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKho"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("NguoiQuanLy")
                        .HasColumnType("int");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKho")
                        .HasName("PK__Kho__3BDA9350F8F4FAC4");

                    b.HasIndex("NguoiQuanLy");

                    b.ToTable("Kho", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.KiemKeKho", b =>
                {
                    b.Property<int>("MaPhieuKK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuKK"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaKho")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayKiemKe")
                        .HasColumnType("date");

                    b.Property<int?>("NguoiKiemKe")
                        .HasColumnType("int");

                    b.Property<string>("SoPhieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang kiểm kê");

                    b.HasKey("MaPhieuKK")
                        .HasName("PK__KiemKeKh__880EE8E856CE8FF5");

                    b.HasIndex("MaKho");

                    b.HasIndex("NguoiKiemKe");

                    b.HasIndex(new[] { "SoPhieu" }, "UQ__KiemKeKh__960AAEE3724913EE")
                        .IsUnique();

                    b.ToTable("KiemKeKho", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.LichSuSuCo", b =>
                {
                    b.Property<int>("MaSuCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSuCo"));

                    b.Property<string>("GiaiPhap")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MucDo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime");

                    b.Property<int?>("NguoiBaoCao")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianPhatHien")
                        .HasColumnType("datetime");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa xử lý");

                    b.HasKey("MaSuCo")
                        .HasName("PK__LichSuSu__A69DF79FCA6E092E");

                    b.HasIndex("MaThietBi");

                    b.HasIndex("NguoiBaoCao");

                    b.ToTable("LichSuSuCo", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.LoaiThietBi", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieuChuanAnToan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiThie__730A5759B88BB5B9");

                    b.ToTable("LoaiThietBi", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.LoaiVatTu", b =>
                {
                    b.Property<int>("MaLoaiVT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiVT"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoaiVT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiVT")
                        .HasName("PK__LoaiVatT__1224E204BED8466A");

                    b.ToTable("LoaiVatTu", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaND")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaND"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<int?>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhongBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaND")
                        .HasName("PK__NguoiDun__2725D724AAEA6ADE");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaQuyen");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__NguoiDun__55F68FC076A218F8")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNCC"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NguoiLienHe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaNCC")
                        .HasName("PK__NhaCungC__3A185DEBE6AFAA11");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhongBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MaNV")
                        .HasName("PK__NhanVien__2725D70AA3601EA0");

                    b.HasIndex("UserID");

                    b.HasIndex(new[] { "Email" }, "UQ__NhanVien__A9D105344A132BAD")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.PhanQuyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuyen")
                        .HasName("PK__PhanQuye__1D4B7ED443CB0F65");

                    b.ToTable("PhanQuyen", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.PhieuBaoTri", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaKeHoach")
                        .HasColumnType("int");

                    b.Property<int?>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayXacNhan")
                        .HasColumnType("datetime");

                    b.Property<int?>("NguoiXacNhan")
                        .HasColumnType("int");

                    b.Property<int?>("NhanVienThucHien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime");

                    b.Property<string>("TinhTrangSauBT")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TinhTrangTruocBT")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ xác nhận");

                    b.HasKey("MaPhieu")
                        .HasName("PK__PhieuBao__2660BFE02A7774C5");

                    b.HasIndex("MaKeHoach");

                    b.HasIndex("MaThietBi");

                    b.HasIndex("NguoiXacNhan");

                    b.HasIndex("NhanVienThucHien");

                    b.ToTable("PhieuBaoTri", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.PhieuNhapKho", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaKhoNhap")
                        .HasColumnType("int");

                    b.Property<int?>("MaNCC")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayHoaDon")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiGiaoHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NguoiLapPhieu")
                        .HasColumnType("int");

                    b.Property<string>("SoHoaDon")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SoPhieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đã hoàn thành");

                    b.HasKey("MaPhieuNhap")
                        .HasName("PK__PhieuNha__1470EF3B2B4F1850");

                    b.HasIndex("MaKhoNhap");

                    b.HasIndex("MaNCC");

                    b.HasIndex("NguoiLapPhieu");

                    b.HasIndex(new[] { "SoPhieu" }, "UQ__PhieuNha__960AAEE3AF547A17")
                        .IsUnique();

                    b.ToTable("PhieuNhapKho", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.PhieuXuatKho", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuXuat"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDoXuat")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaKhoXuat")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhieuBaoTri")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("NguoiLapPhieu")
                        .HasColumnType("int");

                    b.Property<string>("NguoiNhanHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoPhieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đã hoàn thành");

                    b.HasKey("MaPhieuXuat")
                        .HasName("PK__PhieuXua__26C4B5A2FE7B5A65");

                    b.HasIndex("MaKhoXuat");

                    b.HasIndex("MaPhieuBaoTri");

                    b.HasIndex("NguoiLapPhieu");

                    b.HasIndex(new[] { "SoPhieu" }, "UQ__PhieuXua__960AAEE32DB10CF7")
                        .IsUnique();

                    b.ToTable("PhieuXuatKho", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.ThietBi", b =>
                {
                    b.Property<int>("MaThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThietBi"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MaSo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("NgayHetHanBaoHanh")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayLapDat")
                        .HasColumnType("date");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TinhTrang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang hoạt động");

                    b.Property<string>("ViTriLapDat")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThietBi")
                        .HasName("PK__ThietBi__8AEC71F793B7F867");

                    b.HasIndex("MaLoai");

                    b.HasIndex(new[] { "MaSo" }, "UQ__ThietBi__2725087C40D5B15D")
                        .IsUnique();

                    b.ToTable("ThietBi", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.TonKho", b =>
                {
                    b.Property<int>("MaTonKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTonKho"));

                    b.Property<int?>("MaKho")
                        .HasColumnType("int");

                    b.Property<int?>("MaVT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("SoLuongKhaDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("SoLuongToiThieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ViTriLuuTru")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTonKho")
                        .HasName("PK__TonKho__2D970FAAD1B1B4E2");

                    b.HasIndex("MaVT");

                    b.HasIndex(new[] { "MaKho", "MaVT" }, "UQ__TonKho__C9A8C252169D38F0")
                        .IsUnique()
                        .HasFilter("[MaKho] IS NOT NULL AND [MaVT] IS NOT NULL");

                    b.ToTable("TonKho", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.VatTu", b =>
                {
                    b.Property<int>("MaVT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVT"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("MaDVT")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiVT")
                        .HasColumnType("int");

                    b.Property<int?>("MaNCC")
                        .HasColumnType("int");

                    b.Property<string>("MaVach")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("TenVT")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ThoiGianBaoHanh")
                        .HasColumnType("int");

                    b.HasKey("MaVT")
                        .HasName("PK__VatTu__2725103E8899EE53");

                    b.HasIndex("MaDVT");

                    b.HasIndex("MaLoaiVT");

                    b.HasIndex("MaNCC");

                    b.HasIndex("NguoiTao");

                    b.HasIndex(new[] { "MaVach" }, "UQ__VatTu__8BBF4A1C9A1AEDA5")
                        .IsUnique()
                        .HasFilter("[MaVach] IS NOT NULL");

                    b.ToTable("VatTu", (string)null);
                });

            modelBuilder.Entity("BilcoManagement.Models.ChiTietDieuChuyen", b =>
                {
                    b.HasOne("BilcoManagement.Models.DieuChuyenKho", "MaDieuChuyenNavigation")
                        .WithMany("ChiTietDieuChuyens")
                        .HasForeignKey("MaDieuChuyen")
                        .HasConstraintName("FK__ChiTietDi__MaDie__114A936A");

                    b.HasOne("BilcoManagement.Models.VatTu", "MaVTNavigation")
                        .WithMany("ChiTietDieuChuyens")
                        .HasForeignKey("MaVT")
                        .HasConstraintName("FK__ChiTietDie__MaVT__123EB7A3");

                    b.Navigation("MaDieuChuyenNavigation");

                    b.Navigation("MaVTNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.ChiTietKiemKe", b =>
                {
                    b.HasOne("BilcoManagement.Models.KiemKeKho", "MaPhieuKKNavigation")
                        .WithMany("ChiTietKiemKes")
                        .HasForeignKey("MaPhieuKK")
                        .HasConstraintName("FK__ChiTietKi__MaPhi__1AD3FDA4");

                    b.HasOne("BilcoManagement.Models.VatTu", "MaVTNavigation")
                        .WithMany("ChiTietKiemKes")
                        .HasForeignKey("MaVT")
                        .HasConstraintName("FK__ChiTietKie__MaVT__1BC821DD");

                    b.Navigation("MaPhieuKKNavigation");

                    b.Navigation("MaVTNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("BilcoManagement.Models.PhieuNhapKho", "MaPhieuNhapNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .HasConstraintName("FK__ChiTietPh__MaPhi__797309D9");

                    b.HasOne("BilcoManagement.Models.VatTu", "MaVTNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaVT")
                        .HasConstraintName("FK__ChiTietPhi__MaVT__7A672E12");

                    b.Navigation("MaPhieuNhapNavigation");

                    b.Navigation("MaVTNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("BilcoManagement.Models.PhieuXuatKho", "MaPhieuXuatNavigation")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaPhieuXuat")
                        .HasConstraintName("FK__ChiTietPh__MaPhi__04E4BC85");

                    b.HasOne("BilcoManagement.Models.VatTu", "MaVTNavigation")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaVT")
                        .HasConstraintName("FK__ChiTietPhi__MaVT__05D8E0BE");

                    b.Navigation("MaPhieuXuatNavigation");

                    b.Navigation("MaVTNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.ChiTietPhuTung", b =>
                {
                    b.HasOne("BilcoManagement.Models.PhieuBaoTri", "MaPhieuNavigation")
                        .WithMany("ChiTietPhuTungs")
                        .HasForeignKey("MaPhieu")
                        .HasConstraintName("FK__ChiTietPh__MaPhi__236943A5");

                    b.Navigation("MaPhieuNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.DieuChuyenKho", b =>
                {
                    b.HasOne("BilcoManagement.Models.Kho", "MaKhoNhanNavigation")
                        .WithMany("DieuChuyenKhoMaKhoNhanNavigations")
                        .HasForeignKey("MaKhoNhan")
                        .HasConstraintName("FK__DieuChuye__MaKho__0B91BA14");

                    b.HasOne("BilcoManagement.Models.Kho", "MaKhoXuatNavigation")
                        .WithMany("DieuChuyenKhoMaKhoXuatNavigations")
                        .HasForeignKey("MaKhoXuat")
                        .HasConstraintName("FK__DieuChuye__MaKho__0A9D95DB");

                    b.HasOne("BilcoManagement.Models.NhanVien", "NguoiLapPhieuNavigation")
                        .WithMany("DieuChuyenKhoNguoiLapPhieuNavigations")
                        .HasForeignKey("NguoiLapPhieu")
                        .HasConstraintName("FK__DieuChuye__Nguoi__0C85DE4D");

                    b.HasOne("BilcoManagement.Models.NhanVien", "NguoiNhanHangNavigation")
                        .WithMany("DieuChuyenKhoNguoiNhanHangNavigations")
                        .HasForeignKey("NguoiNhanHang")
                        .HasConstraintName("FK__DieuChuye__Nguoi__0D7A0286");

                    b.Navigation("MaKhoNhanNavigation");

                    b.Navigation("MaKhoXuatNavigation");

                    b.Navigation("NguoiLapPhieuNavigation");

                    b.Navigation("NguoiNhanHangNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.HinhAnhBaoTri", b =>
                {
                    b.HasOne("BilcoManagement.Models.PhieuBaoTri", "MaPhieuNavigation")
                        .WithMany("HinhAnhBaoTris")
                        .HasForeignKey("MaPhieu")
                        .HasConstraintName("FK__HinhAnhBa__MaPhi__2739D489");

                    b.Navigation("MaPhieuNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.KeHoachBaoTri", b =>
                {
                    b.HasOne("BilcoManagement.Models.ThietBi", "MaThietBiNavigation")
                        .WithMany("KeHoachBaoTris")
                        .HasForeignKey("MaThietBi")
                        .HasConstraintName("FK__KeHoachBa__MaThi__4316F928");

                    b.HasOne("BilcoManagement.Models.NhanVien", "NguoiTaoNavigation")
                        .WithMany("KeHoachBaoTris")
                        .HasForeignKey("NguoiTao")
                        .HasConstraintName("FK__KeHoachBa__Nguoi__44FF419A");

                    b.Navigation("MaThietBiNavigation");

                    b.Navigation("NguoiTaoNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.Kho", b =>
                {
                    b.HasOne("BilcoManagement.Models.NhanVien", "NguoiQuanLyNavigation")
                        .WithMany("Khos")
                        .HasForeignKey("NguoiQuanLy")
                        .HasConstraintName("FK__Kho__NguoiQuanLy__5CD6CB2B");

                    b.Navigation("NguoiQuanLyNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.KiemKeKho", b =>
                {
                    b.HasOne("BilcoManagement.Models.Kho", "MaKhoNavigation")
                        .WithMany("KiemKeKhos")
                        .HasForeignKey("MaKho")
                        .HasConstraintName("FK__KiemKeKho__MaKho__160F4887");

                    b.HasOne("BilcoManagement.Models.NhanVien", "NguoiKiemKeNavigation")
                        .WithMany("KiemKeKhos")
                        .HasForeignKey("NguoiKiemKe")
                        .HasConstraintName("FK__KiemKeKho__Nguoi__17036CC0");

                    b.Navigation("MaKhoNavigation");

                    b.Navigation("NguoiKiemKeNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.LichSuSuCo", b =>
                {
                    b.HasOne("BilcoManagement.Models.ThietBi", "MaThietBiNavigation")
                        .WithMany("LichSuSuCos")
                        .HasForeignKey("MaThietBi")
                        .HasConstraintName("FK__LichSuSuC__MaThi__1EA48E88");

                    b.HasOne("BilcoManagement.Models.NhanVien", "NguoiBaoCaoNavigation")
                        .WithMany("LichSuSuCos")
                        .HasForeignKey("NguoiBaoCao")
                        .HasConstraintName("FK__LichSuSuC__Nguoi__1F98B2C1");

                    b.Navigation("MaThietBiNavigation");

                    b.Navigation("NguoiBaoCaoNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.NguoiDung", b =>
                {
                    b.HasOne("BilcoManagement.Models.NhanVien", "MaNVNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaNV")
                        .HasConstraintName("FK__NguoiDung__MaNV__6B24EA82");

                    b.HasOne("BilcoManagement.Models.PhanQuyen", "MaQuyenNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaQuyen")
                        .HasConstraintName("FK__NguoiDung__MaQuy__6C190EBB");

                    b.Navigation("MaNVNavigation");

                    b.Navigation("MaQuyenNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.NhanVien", b =>
                {
                    b.HasOne("BilcoManagement.Models.NguoiDung", "User")
                        .WithMany("NhanViens")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK_NhanVien_NguoiDung");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BilcoManagement.Models.PhieuBaoTri", b =>
                {
                    b.HasOne("BilcoManagement.Models.KeHoachBaoTri", "MaKeHoachNavigation")
                        .WithMany("PhieuBaoTris")
                        .HasForeignKey("MaKeHoach")
                        .HasConstraintName("FK__PhieuBaoT__MaKeH__48CFD27E");

                    b.HasOne("BilcoManagement.Models.ThietBi", "MaThietBiNavigation")
                        .WithMany("PhieuBaoTris")
                        .HasForeignKey("MaThietBi")
                        .HasConstraintName("FK__PhieuBaoT__MaThi__49C3F6B7");

                    b.HasOne("BilcoManagement.Models.NhanVien", "NguoiXacNhanNavigation")
                        .WithMany("PhieuBaoTriNguoiXacNhanNavigations")
                        .HasForeignKey("NguoiXacNhan")
                        .HasConstraintName("FK__PhieuBaoT__Nguoi__4BAC3F29");

                    b.HasOne("BilcoManagement.Models.NhanVien", "NhanVienThucHienNavigation")
                        .WithMany("PhieuBaoTriNhanVienThucHienNavigations")
                        .HasForeignKey("NhanVienThucHien")
                        .HasConstraintName("FK__PhieuBaoT__NhanV__4AB81AF0");

                    b.Navigation("MaKeHoachNavigation");

                    b.Navigation("MaThietBiNavigation");

                    b.Navigation("NguoiXacNhanNavigation");

                    b.Navigation("NhanVienThucHienNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.PhieuNhapKho", b =>
                {
                    b.HasOne("BilcoManagement.Models.Kho", "MaKhoNhapNavigation")
                        .WithMany("PhieuNhapKhos")
                        .HasForeignKey("MaKhoNhap")
                        .HasConstraintName("FK__PhieuNhap__MaKho__72C60C4A");

                    b.HasOne("BilcoManagement.Models.NhaCungCap", "MaNCCNavigation")
                        .WithMany("PhieuNhapKhos")
                        .HasForeignKey("MaNCC")
                        .HasConstraintName("FK__PhieuNhap__MaNCC__73BA3083");

                    b.HasOne("BilcoManagement.Models.NhanVien", "NguoiLapPhieuNavigation")
                        .WithMany("PhieuNhapKhos")
                        .HasForeignKey("NguoiLapPhieu")
                        .HasConstraintName("FK__PhieuNhap__Nguoi__75A278F5");

                    b.Navigation("MaKhoNhapNavigation");

                    b.Navigation("MaNCCNavigation");

                    b.Navigation("NguoiLapPhieuNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.PhieuXuatKho", b =>
                {
                    b.HasOne("BilcoManagement.Models.Kho", "MaKhoXuatNavigation")
                        .WithMany("PhieuXuatKhos")
                        .HasForeignKey("MaKhoXuat")
                        .HasConstraintName("FK__PhieuXuat__MaKho__7F2BE32F");

                    b.HasOne("BilcoManagement.Models.PhieuBaoTri", "MaPhieuBaoTriNavigation")
                        .WithMany("PhieuXuatKhos")
                        .HasForeignKey("MaPhieuBaoTri")
                        .HasConstraintName("FK__PhieuXuat__MaPhi__00200768");

                    b.HasOne("BilcoManagement.Models.NhanVien", "NguoiLapPhieuNavigation")
                        .WithMany("PhieuXuatKhos")
                        .HasForeignKey("NguoiLapPhieu")
                        .HasConstraintName("FK__PhieuXuat__Nguoi__01142BA1");

                    b.Navigation("MaKhoXuatNavigation");

                    b.Navigation("MaPhieuBaoTriNavigation");

                    b.Navigation("NguoiLapPhieuNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.ThietBi", b =>
                {
                    b.HasOne("BilcoManagement.Models.LoaiThietBi", "MaLoaiNavigation")
                        .WithMany("ThietBis")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK__ThietBi__MaLoai__3F466844");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.TonKho", b =>
                {
                    b.HasOne("BilcoManagement.Models.Kho", "MaKhoNavigation")
                        .WithMany("TonKhos")
                        .HasForeignKey("MaKho")
                        .HasConstraintName("FK__TonKho__MaKho__60A75C0F");

                    b.HasOne("BilcoManagement.Models.VatTu", "MaVTNavigation")
                        .WithMany("TonKhos")
                        .HasForeignKey("MaVT")
                        .HasConstraintName("FK__TonKho__MaVT__619B8048");

                    b.Navigation("MaKhoNavigation");

                    b.Navigation("MaVTNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.VatTu", b =>
                {
                    b.HasOne("BilcoManagement.Models.DonViTinh", "MaDVTNavigation")
                        .WithMany("VatTus")
                        .HasForeignKey("MaDVT")
                        .HasConstraintName("FK__VatTu__MaDVT__571DF1D5");

                    b.HasOne("BilcoManagement.Models.LoaiVatTu", "MaLoaiVTNavigation")
                        .WithMany("VatTus")
                        .HasForeignKey("MaLoaiVT")
                        .HasConstraintName("FK__VatTu__MaLoaiVT__5629CD9C");

                    b.HasOne("BilcoManagement.Models.NhaCungCap", "MaNCCNavigation")
                        .WithMany("VatTus")
                        .HasForeignKey("MaNCC")
                        .HasConstraintName("FK__VatTu__MaNCC__5812160E");

                    b.HasOne("BilcoManagement.Models.NhanVien", "NguoiTaoNavigation")
                        .WithMany("VatTus")
                        .HasForeignKey("NguoiTao")
                        .HasConstraintName("FK__VatTu__NguoiTao__59FA5E80");

                    b.Navigation("MaDVTNavigation");

                    b.Navigation("MaLoaiVTNavigation");

                    b.Navigation("MaNCCNavigation");

                    b.Navigation("NguoiTaoNavigation");
                });

            modelBuilder.Entity("BilcoManagement.Models.DieuChuyenKho", b =>
                {
                    b.Navigation("ChiTietDieuChuyens");
                });

            modelBuilder.Entity("BilcoManagement.Models.DonViTinh", b =>
                {
                    b.Navigation("VatTus");
                });

            modelBuilder.Entity("BilcoManagement.Models.KeHoachBaoTri", b =>
                {
                    b.Navigation("PhieuBaoTris");
                });

            modelBuilder.Entity("BilcoManagement.Models.Kho", b =>
                {
                    b.Navigation("DieuChuyenKhoMaKhoNhanNavigations");

                    b.Navigation("DieuChuyenKhoMaKhoXuatNavigations");

                    b.Navigation("KiemKeKhos");

                    b.Navigation("PhieuNhapKhos");

                    b.Navigation("PhieuXuatKhos");

                    b.Navigation("TonKhos");
                });

            modelBuilder.Entity("BilcoManagement.Models.KiemKeKho", b =>
                {
                    b.Navigation("ChiTietKiemKes");
                });

            modelBuilder.Entity("BilcoManagement.Models.LoaiThietBi", b =>
                {
                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("BilcoManagement.Models.LoaiVatTu", b =>
                {
                    b.Navigation("VatTus");
                });

            modelBuilder.Entity("BilcoManagement.Models.NguoiDung", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("BilcoManagement.Models.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhapKhos");

                    b.Navigation("VatTus");
                });

            modelBuilder.Entity("BilcoManagement.Models.NhanVien", b =>
                {
                    b.Navigation("DieuChuyenKhoNguoiLapPhieuNavigations");

                    b.Navigation("DieuChuyenKhoNguoiNhanHangNavigations");

                    b.Navigation("KeHoachBaoTris");

                    b.Navigation("Khos");

                    b.Navigation("KiemKeKhos");

                    b.Navigation("LichSuSuCos");

                    b.Navigation("NguoiDungs");

                    b.Navigation("PhieuBaoTriNguoiXacNhanNavigations");

                    b.Navigation("PhieuBaoTriNhanVienThucHienNavigations");

                    b.Navigation("PhieuNhapKhos");

                    b.Navigation("PhieuXuatKhos");

                    b.Navigation("VatTus");
                });

            modelBuilder.Entity("BilcoManagement.Models.PhanQuyen", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("BilcoManagement.Models.PhieuBaoTri", b =>
                {
                    b.Navigation("ChiTietPhuTungs");

                    b.Navigation("HinhAnhBaoTris");

                    b.Navigation("PhieuXuatKhos");
                });

            modelBuilder.Entity("BilcoManagement.Models.PhieuNhapKho", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("BilcoManagement.Models.PhieuXuatKho", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("BilcoManagement.Models.ThietBi", b =>
                {
                    b.Navigation("KeHoachBaoTris");

                    b.Navigation("LichSuSuCos");

                    b.Navigation("PhieuBaoTris");
                });

            modelBuilder.Entity("BilcoManagement.Models.VatTu", b =>
                {
                    b.Navigation("ChiTietDieuChuyens");

                    b.Navigation("ChiTietKiemKes");

                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("ChiTietPhieuXuats");

                    b.Navigation("TonKhos");
                });
#pragma warning restore 612, 618
        }
    }
}
